### ISSUE TITLE
See if Info.plist location needs to be fixed

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/swift3-module-template#11]
This is a bug with Xcode. It is addressed in the recipe. But I needed to also use this manual fix:

https://github.com/fulldecent/FDTake/commit/9cc0940637a87ed988e9a0a491bd6dc2e3a1f1e1

Not sure if the recipe needs to be updated further. Hoping for another pair of eyes to verify.

**Comment by bulusoy** [comment]
See #15 :)

**Comment by fulldecent** [comment]
This is addressed in the "bug/workaround with Xcode" part of the Recipe now, closing.
