### ISSUE TITLE
path to the *.framework in the related example app

### ISSUE THREAD

**Issue by annawidera** [fulldecent/swift3-module-template#14]
### path to the Example.framework
I had an issue with the **path to the Example.framework**. 

In the iOS Example generated project path to the Example.framework was set to **"Relative to Group"**. 
At the same time in the Xcode Preferences (tab: Locations) I had Derived Data location set to Default (/Users/aniawidera/Library/Developer/Xcode/DerivedData). 
When I built the Example.framework it was not within Example workspace directory. 

###  issue with launching an iOS Example app on the device
I had also an issue with launching an iOS Example app on the device. 
The error was: `Library not found`. 
I noticed that Example.framework was added only as **Linked Frameworks and Libraries** (Project iOS Example --> Target iOS Example --> tab: General).
I got it working eventually by adding the Example.framework also to the Embedded Binaries but I am not sure if it is the best solution? 

Thank you for your effort! Any help will be greatly appreciated.

**Comment by fulldecent** [comment]
Hmmm, thank you for the feedback! I have made many corrections in the latest 8.1 version today. Could you please confirm if this issue still exists for the latest version? If so, may I bother you to make screenshots of these screens, this would help me to troubleshoot.

**Comment by fulldecent** [comment]
I'm closing now as I think this is fixed in the latest version. Please reopen if still broken.
