### ISSUE TITLE
Adding ObjC file to template

### ISSUE THREAD

**Issue by DZozulya** [fulldecent/swift3-module-template#36]
Hey,

Thanks a lot for merging my pull request https://github.com/fulldecent/swift3-module-template/pull/35

I have a question after merging - should I add one ObjC class to the template, so it would be obvious for users how to add objc files and have interoperability with swift code? What do you think?

P.S. I think that this template can be universal for both languages. Ofc example and tests will still be in Swift, which is not a problem for me.

**Comment by fulldecent** [comment]
This is a great idea and it will let me /finally/ merge into pod-template.

Can you think of a classy, not contrived, way to add another ObjC file in there?

**Comment by DZozulya** [comment]
Can you clarify what do you mean by "classy"? I'm not sure I get what you mean :)

P.S. My idea was to add a file with ObjC code to "Add source code with some functionality to the module" recipe step.

**Comment by fulldecent** [comment]
The current example code displays a chess piece. The new code should also do something useful, not just print "hello world".

**Comment by fulldecent** [comment]
Fixed in #37, thank you!
